# spring
spring:
  # application
  application:
    name: ${artifactId}
  # profiles
  profiles:
    active: local
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://${db.server}/DATABASE_NAME?${mysql.url.params}
      username: ${db.username}
      password: ${db.password}
# framework
framework:
  # swagger
  swagger:
    base-package: ${groupId}.${artifactId}.web.controller
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    ${groupId}.${artifactId}: info
# mybatis plus
mybatis-plus:
  type-aliases-package: ${groupId}.${artifactId}.entity,${groupId}.${artifactId}.model.*
  mapper-locations: classpath:mappers/*Mapper.xml
# mysql
mysql:
  url:
    params: useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
