# spring
spring:
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://host:port/database?${mysql.url.params}
      username:
      password:
# framework
framework:
  # swagger
  swagger:
    enabled: false
